POST http://localhost:3001/api/blogs HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2aSBIYUdhZG9sIiwiaWQiOjEsImlhdCI6MTY0MTkxODcwMn0.YUyIeSwq6WmBAZCDsd21YdlFA8a2MefZnExwBiCDGoA
Content-Type: application/json

{
    "author": "von bamper",
    "title": "vonton",
    "url":"vonton.com",
    "likes": 15
}

###

GET http://localhost:3001/api/blogs HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2aSBIYUdhZG9sIiwiaWQiOjEsImlhdCI6MTY0MTkxODcwMn0.YUyIeSwq6WmBAZCDsd21YdlFA8a2MefZnExwBiCDGoA
###

###
GET http://localhost:3001/api/author?order=DESC
###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "id": 10,
    "username": "aviz@asd.com",
    "name": "ziv123"
}

###
GET http://localhost:3001/api/users HTTP/1.1

### 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "avi HaGadol",
    "password": "secret"
}

###
PUT  http://localhost:3001/api/users/ziv125 HTTP/1.1
Content-Type: application/json

{
    "newUserName": "avi HaGadol1"
}

###
DELETE http://localhost:3001/api/blogs/8 HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2aSBIYUdhZG9sIiwiaWQiOjEsImlhdCI6MTY0MTkxODcwMn0.YUyIeSwq6WmBAZCDsd21YdlFA8a2MefZnExwBiCDGoA

