POST http://localhost:3001/api/blogs HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pc2ltQGEuY29tIiwiaWQiOjEyLCJpYXQiOjE2NDIwMDExMzd9.IJBiOFdrtK0hqg2Ivg7e8m4cWq7mtrLdfs-WjL1fjdI
Content-Type: application/json

{
    "author": "von bamper",
    "title": "vonton",
    "url":"vonton.com",
    "likes": 15
}

###

GET http://localhost:3001/api/blogs HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pc2ltQGEuY29tIiwiaWQiOjEyLCJpYXQiOjE2NDIwMDExMzd9.IJBiOFdrtK0hqg2Ivg7e8m4cWq7mtrLdfs-WjL1fjdI
###

###
GET http://localhost:3001/api/author?order=DESC
###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "id": 12,
    "username": "nisim@aasd.com",
    "name": "abu kabir"
}

###
GET http://localhost:3001/api/users HTTP/1.1

### 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "nisim@a.com",
    "password": "secret"
}

###
PUT  http://localhost:3001/api/users/ziv125 HTTP/1.1
Content-Type: application/json

{
    "newUserName": "avi HaGadol1"
}

###
DELETE http://localhost:3001/api/blogs/8 HTTP/1.1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pc2ltQGEuY29tIiwiaWQiOjEyLCJpYXQiOjE2NDIwMDExMzd9.IJBiOFdrtK0hqg2Ivg7e8m4cWq7mtrLdfs-WjL1fjdI

